FROM slackapiexport_base

VOLUME /opt/slack-api-export/var/logs
VOLUME /opt/slack-api-export/var/export

COPY ./src /opt/slack-api-export
WORKDIR /opt/slack-api-export

CMD [ "./bin/console", "slack:export", "/opt/slack-api-export/var/export", "--env=prod" ]