FROM slackapiexport_base

VOLUME /opt/slack-api-export/var/logs

COPY ./src /opt/slack-api-export
WORKDIR /opt/slack-api-export

# Expose and run the build in php web server
EXPOSE 8000

CMD [ "./bin/console", "server:run", "0.0.0.0:8000", "--env=prod" ]