FROM php:5.6-cli

WORKDIR /opt/slack-api-export

COPY config/php.ini /usr/local/etc/php/

# Install mongo client libraries
RUN apt-get update && \
    apt-get install -y libssl-dev && \
    pecl install mongo && \
    docker-php-ext-enable mongo

# Expose and run the build in php web server
EXPOSE 8000
CMD [ "./bin/console", "server:run", "0.0.0.0:8000", "--env=prod" ]