<?php

namespace AppBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * User
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{

}
