<?php

namespace AppBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Auth
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AuthRepository extends DocumentRepository
{
}
