<?php

namespace AppBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Channel
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends DocumentRepository
{
}
